### ISSUE TITLE
Counter the current spamwave using @a.gup.pe-Bots for spreading

### ISSUE THREAD

**Issue by alsternerd** [immers-space/guppe#104]
Please admin/moderate a.gup.pe and block spam, if it happens or is seen on the Fediverse.

Some instances the spammers use are: social.cutefunny.net (warning: CP), cunnyborea.top, m.mxin.moe, friendsyu.me
Maybe more, these are the ones mentioned by @ErikUden@mastodon.de in https://mastodon.de/@ErikUden/111938259652720963 .

I read they are using specific usernames, maybe please try to also filter these.

Thank you.

**Comment by wmurphyrd** [comment]
Thank you for the report. I put the first 2 in the blocklist for guppe. 

According to [Erik's current list](https://github.com/Mastodon-DE/blocklists/blob/main/spam/2024-02-15/2024-02-15-spam-mute-list.md#refederate-with-or-unmute--spam-stopped), the latter two have resolved their spam problem and are safe to federate again, so I did not add them. Please let me know if problems continue
