### ISSUE TITLE
auto-boosts not working?

### ISSUE THREAD

**Issue by signnd** [immers-space/guppe#68]
really sorry for not being too specific or if I did something wrong. I wish to contact personally but can't seem to find a way. auto-boosts does not seem to work, could anyone look into that?

Earlier I wanted to delete my post that got boosted by the group, but I mistakenly deleted it from the boost, not the actual post. Once again I'm sorry 😭

**Comment by wmurphyrd** [comment]
I'm sorry, but I don't understand the issue. You can contact me on fedi: datatitian@social.coop
