### ISSUE TITLE
Unable to Follow Guppe Groups

### ISSUE THREAD

**Issue by XenonFiber** [immers-space/guppe#78]
I've tried to follow a group on two separate v4.0.2 Mastodon instances, and it appears to go through, but refreshing the page makes the button go from "Unfollow" to "Widthdraw Follow Request".

I don't think the follows are going through properly.

-- Freya Raccooncat (she/her)

**Comment by wmurphyrd** [comment]
Sometimes the acceptance takes a little bit to go through. I just checked and the backlog is currently empty. Would you please refresh again and see if it shows following now?

**Comment by wmurphyrd** [comment]
Yes that info could help, although I'm traveling for the holidays and won't be able to check soon. If you'd prefer not to post it publicly here, you can dm me @datatitian@social.coop

You may also try withdrawing and following again, as it seems your previous requests were lost

**Comment by wmurphyrd** [comment]
I think we determined this to be an admin issue with the Mastodon sever in question.
